const countries = {
  "Argentina": "ARG",
  "Austrália": "AUS",
  "Bélgica": "BEL",
  "Brasil": "BRA",
  "Camarões": "CMR",
  "Canadá": "CAN",
  "Costa Rica": "CRC",
  "Croácia": "CRO",
  "Dinamarca": "DEN",
  "Equador": "ECU",
  "Inglaterra": "ENG",
  "França": "FRA",
  "Alemanha": "GER",
  "Gana": "GHA",
  "Irã": "IRN",
  "Japão": "JPN",
  "Coreia do Sul": "KOR",
  "México": "MEX",
  "Marrocos": "MAR",
  "Holanda": "NED",
  "Polônia": "POL",
  "Portugal": "POR",
  "Catar": "QAT",
  "Arábia Saudita": "KSA",
  "Senegal": "SEN",
  "Sérvia": "SRB",
  "Espanha": "ESP",
  "Suíça": "SUI",
  "Tunísia": "TUN",
  "EUA": "USA",
  "Uruguai": "URU",
  "Gales": "WAL"
};

export default countries;
